<footer class="footer fixed-bottom">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <p>&copy; <?php echo date("Y"); ?> CorpU</p>
      </div>
      <div class="col-md-6">
        <ul class="list-inline text-md-right">
          <li class="list-inline-item"><a href="index.php">Home</a></li>
          <li class="list-inline-item"><a href="#">About</a></li>
          <li class="list-inline-item"><a href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>